apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-management-api-deployment
  labels:
    app: media-management-api
spec:
  selector:
    matchLabels: 
      app: media-management-api
  template:
    metadata:
      labels:
        app: media-management-api
    spec:
      containers:
        - name: c-media-management-api
          image: "#{APP_IMAGE}#"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 25
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: S3BUCKETOPTIONS__VIDEOSBUCKET
              value: videos-bucket-soat72025
            - name: S3BUCKETOPTIONS__ZIPFILESBUCKET
              value: zip-images-bucket-soat72025
            - name: RUNMIGRATIONSONSTARTUP
              value: 'true'
            - name: CONNECTIONSTRINGS__DEFAULTCONNECTION
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: connection-string
            - name: COGNITOAUTHENTICATIONOPTIONS__USERPOOLID
              value: us-east-1_2ikmPdEFY
            - name: COGNITOAUTHENTICATIONOPTIONS__COGNITODOMAIN              
              value: https://dotvideos-1.auth.us-east-1.amazoncognito.com/
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: aws-access-key-id 
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: aws-secret-access-key 
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: aws-session-token 
