apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-management-api-deployment
  labels:
    app: media-management-api
spec:
  selector:
    matchLabels: 
      app: media-management-api
  template:
    metadata:
      labels:
        app: media-management-api
    spec:
      containers:
        - name: c-media-management-api
          image: "#{APP_IMAGE}#"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 25
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
            failureThreshold: 3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: S3BucketOptions__VideosBucket
              value: "#{VIDEOS_BUCKET_NAME}#"
            - name: S3BucketOptions__ZipFilesBucket
              value: "#{ZIPFILES_BUCKET_NAME}#"
            - name: RunMigrationsOnStartup
              value: 'true'
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: connection-string
            - name: CognitoAuthenticatiOnoptions__UserpoolId
              value: "#{COGNITO_USER_POOL_ID}#"
            - name: CognitoAuthenticationOptions__CognitoDomain              
              value: "#{COGNITO_USER_POOL_DOMAIN}#"
            - name: SqsMessagePublisherOptions__QueueName
              value: "#{SQS_VIDEOS_TO_PROCESS_QUEUE}#"
            - name: ApiKeyAuthenticationOptions__Keys
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: media-manager-api-keys
            - name: SMTPSenderOptions__Host
              value: "#{SMTP_HOST}#"
            - name: SMTPSenderOptions__Port
              value: "#{SMTP_PORT}#"
            - name: SMTPSenderOptions__User
              value: "#{SMTP_USER}#"
            - name: SMTPSenderOptions__FromEmail
              value: "#{SMTP_FROM_EMAIL}#"
            - name: SMTPSenderOptions__Password
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: smtp-password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: aws-access-key-id 
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: aws-secret-access-key 
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: aws-session-token 
