apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: media-management-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: media-management-api-deployment
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 60