apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-management-api-deployment
  labels:
    app: media-management-api
spec:
  selector:
    matchLabels: 
      app: media-management-api
  template:
    metadata:
      labels:
        app: media-management-api
    spec:
      containers:
        - name: c-media-management-api
          image: "#{APP_IMAGE}#"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 300
            periodSeconds: 60
            failureThreshold: 3
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: S3BUCKETOPTIONS__VIDEOSBUCKET
              value: 98videos-videos-to-process
            - name: S3BUCKETOPTIONS__ZIPFILESBUCKET
              value: 98videos-zip-files
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: aws-access-key-id 
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: aws-secret-access-key 
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef: 
                  name: media-management-api-secrets
                  key: aws-session-token 
