apiVersion: v1
kind: Secret
metadata:
	name: media-management-api-secrets
type: Opaque
stringData:
	connection-string: 
	aws-access-key-id: "#{AWS_ACCESS_KEY_ID}#"
	aws-secret-access-key: "#{AWS_SECRET_ACCESS_KEY}#"
	aws-session-token: "#{AWS_SESSION_TOKEN}#"